"""Auto-built report.html aggregating all pipeline outputs."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def build_report(
    metrics_dir: Path,
    figures_dir: Path,
    symbolic_dir: Path,
    hits_dir: Path,
    out_path: Path,
) -> Path:
    """Generate a self-contained HTML report from all Stage 8-10 outputs."""
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Gather metrics
    metrics_content = ""
    metrics_file = metrics_dir / "evaluation_metrics.json"
    if metrics_file.exists():
        metrics = json.loads(metrics_file.read_text(encoding="utf-8"))
        rows = []
        for model, data in metrics.items():
            m = data.get("metrics", {})
            ci = data.get("bootstrap_ci", {})
            rmse_ci = ci.get("rmse", {})
            rows.append(
                f"<tr><td>{model}</td>"
                f"<td>{m.get('rmse', '?'):.4f}</td>"
                f"<td>[{rmse_ci.get('lo', '?'):.4f}, {rmse_ci.get('hi', '?'):.4f}]</td>"
                f"<td>{m.get('r2', '?'):.4f}</td>"
                f"<td>{m.get('spearman_rho', '?'):.4f}</td></tr>"
            )
        metrics_content = "\n".join(rows)

    # Gather figures
    figures_html = ""
    for svg_path in sorted(figures_dir.glob("*.svg")):
        name = svg_path.stem.replace("_", " ").title()
        try:
            svg_content = svg_path.read_text(encoding="utf-8")
            figures_html += f'<h3>{name}</h3><div class="figure">{svg_content}</div>\n'
        except Exception:
            figures_html += f'<h3>{name}</h3><p>(figure load error)</p>\n'

    # Symbolic equation
    eq_html = ""
    eq_path = symbolic_dir / "pIC50_equation.tex"
    if eq_path.exists():
        eq_tex = eq_path.read_text(encoding="utf-8")
        eq_html = f'<h3>Symbolic pIC50 Equation</h3><pre>{eq_tex}</pre>'

    # Hits summary
    hits_html = ""
    annotated = hits_dir / "annotated_hits.csv"
    if annotated.exists():
        import pandas as pd
        df = pd.read_csv(annotated)
        hits_html = f"<h3>Top Hits ({len(df)} compounds)</h3>\n"
        hits_html += df.head(20).to_html(index=False, classes="hits-table", float_format="%.3f")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BRD4-KAN Report</title>
<style>
body {{ font-family: 'Times New Roman', serif; margin: 40px; background: #fafafa; }}
h1 {{ color: #3C5488; }}
h2 {{ color: #E64B35; border-bottom: 2px solid #E64B35; padding-bottom: 4px; }}
h3 {{ color: #4DBBD5; }}
table {{ border-collapse: collapse; margin: 10px 0; }}
th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: right; }}
th {{ background: #3C5488; color: white; }}
.figure {{ margin: 10px 0; max-width: 100%; overflow-x: auto; }}
.figure svg {{ max-width: 100%; height: auto; }}
.hits-table {{ font-size: 11px; }}
</style>
</head>
<body>
<h1>BRD4-KAN Pipeline Report</h1>

<h2>Evaluation Metrics (scaffold-test, 95% bootstrap CI)</h2>
<table>
<tr><th>Model</th><th>RMSE</th><th>CI</th><th>R&sup2;</th><th>Spearman &rho;</th></tr>
{metrics_content}
</table>

{eq_html}

<h2>Figures</h2>
{figures_html}

<h2>Screening & Hit Analysis</h2>
{hits_html}

<footer><p>Generated by BRD4-KAN pipeline.</p></footer>
</body>
</html>"""

    out_path.write_text(html, encoding="utf-8")
    logger.info("Report written to %s", out_path)
    return out_path
